Repository IT-Start-Gjovik/startgjovik_website, pull requests merged in 2024-02, with the labels that each got.

#305 fix: 'styre' schema added
  backend/schemas/index.ts
Labels: bug, enhancement

#310 Button component
  app/(site)/for-bedrifter/page.tsx
  components/Button/button.tsx
Labels: component

#319 Navbar sidebar
  app/(site)/page.tsx
  app/globals.css
  components/header/page.tsx
  components/navbar/dropDownMenu.tsx
  components/navbar/hambugerMenuItems.ts
  components/navbar/navbar.tsx
Labels: component

#322 fix: add z-index for sidebar depth
  app/(site)/om-oss/page.tsx
  components/navbar/dropDownMenu.tsx
Labels: bug

#334 fix: header stick to hero banner
  components/navbar/navbar.tsx
Labels: bug

#343 hero-component refactor and add sustainability hero
  app/(site)/arrangementer/[eventPage]/page.tsx
  app/(site)/baerekraft/page.tsx
  app/(site)/bli-medlem/page.tsx
  app/(site)/for-bedrifter/page.tsx
  app/(site)/page.tsx
  components/frontPage/frontPage.tsx
  components/frontPage/frontProp.tsx
  components/hero/hero.tsx
  components/hero/heroSection.tsx
  components/home/homeHeroContent.tsx
  components/navbar/navbar.tsx
  components/sustainability/sustainabilityHeroContent.tsx
  components/sustainability/sustainabilityText.tsx
  public/images/sustainability/sustainability-hero-text.jpg
  public/images/sustainability/sustainability-hero.jpg
Labels: enhancement, component
